utils::globalVariables(c("Localidad", "Semana.Epidemiologica", "read.table",
                         "Huevecillos", "data", "NOMBRE", "Pocision_Y",
                         "Pocision_X", "plot", "mesh", "pred_mean", "points",
                         "z_score", "hotspots_eggs", "getis_ord_umbral", "getis_ord_umbral",
                         "getis_ord", "voronoipolygons", "NOMGEO", "long", "AMBITO",
                         "Clave", "Ovitrampa", "Fecha.Lectura",
                         "unzip_read", "unzip", "week", "Municipio", "Entidad", "eggs",
                         "Sector", "Manzana", "sec_manz", "seccion", "manzana", "geometry",
                         "risk", "CVE_ENT",
                         "clave", "hotspots_binary", "intensity",
                         "mpo", "ovitrap", "x", "year"))
